use_frameworks!

platform :ios, '8.0'

target 'ZKUserDefaults_Example' do
  pod 'ZKUserDefaults', :path => '../'

  target 'ZKUserDefaults_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
